#############################################################################################
# These workflows are for demonstrations purposes only and should not be used in production #
#############################################################################################
# To learn more about GitHub Actions, please see the official documentation:                #
# - https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions    #
#                                                                                           #
# To learn more about the actions used, please refer to the GitHub marketplace:             #
# - https://github.com/marketplace                                                          #
#############################################################################################

name: Deploy - Continous Delivery

# The 'on' code block below demonstrates that if branch protections are enabled, that 
# the only time a continuous delivery (CD) workflow will execute is when a pull request
# is merged into the main branch
on: 
  push:
    branches:
      - 'master'

# The 'env' block is used for declaring environment variables that will be used in our 
# workflow. These variables can be recalled by using the expressions syntax '${{ <expression. }}'
# For more information on expressions and retrieving environment variables and secrets, see
# https://docs.github.com/en/actions/learn-github-actions/expressions
env:
  # set this to the name of your container registry
  AZURE_CONTAINER_REGISTRY: orleansbasicsacr1
  # set this to your project's name
  PROJECT_NAME: orleansbasics
  # set this to the resource group containing your AKS cluster
  RESOURCE_GROUP: orleansbasics
  # set this to the name of your AKS cluster
  CLUSTER_NAME: orleansbasics
  # set this to the name pf your container registry url
  REGISTRY_URL: orleansbasicsacr1.azurecr.io
  # set this to the path to your helm file
  MANIFEST_PATH: _manifests/deployment.yaml

jobs:
  docker-build-and-deploy:
    # Defines the runner we want to use for executing this workflow.
    # More about choosing a runner: https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job
    runs-on: ubuntu-latest
    steps:
    # Checkouts the associated repository for this workflow
    - uses: actions/checkout@master

    # Login to Azure using the official action
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Sets default azure container registry using the AZURE_CONTAINER_REGISTRY environment variable
    # then builds the container image on the ACR. We could also build the image using docker tasks,
    # or a docker cli script
    - name: Build image on ACR
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az configure --defaults acr=${{ env.AZURE_CONTAINER_REGISTRY }}
          az acr build -t ${{ env.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:latest .
    
    # Makes sure we have kubectl (kubernetes cli tool) installed on the runner. It should be here, but
    # better safe than sorry...
    - name: Setup Kubectl
      uses: azure/setup-kubectl@v2.0

    # Pulls the kubeconfig file and sets it as the default context for executing kubectl commands against
    - name: Gets K8s context
      uses: azure/aks-set-context@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

    # Deploy our application using the manifest file found at the path defined in the MANIFEST_PATH 
    # environment variable
    - name: Deploy our Orleans application!
      uses: Azure/k8s-deploy@v1.4
      with:
        manifests: ${{ env.MANIFEST_PATH }}
